### ISSUE TITLE
Count-based vs raw accelerometer

### ISSUE THREAD

**Issue by ghammad** [cdsig/CDSIG-Project#2]
The modification of Tara made me think that we might need to clarify our intent:

do we aim to provide a standard and acquisition guidelines for data acquired with count-based devices or should we aim to provide a unified framework for both count-based and raw accelerometer?

My feeling is that it will make our journey more complicated, sure, but I think we cannot afford not to do so as the revolution (count-based -> raw accelerometer) is happening and our standard should be aligned with that revolution.

WDYT?

**Comment by jcolomb** [comment]
I am not sure to be welcome to the discussion, but as a professional data manager, there is an extra point I would like to make, a legal one. At least in Germany, raw data has to be archived for 10 years.
For exapmle: It  brings difficulties for imaging data that want to use BIDS as the data should officially be saved in the raw "source" format, and in the NIFTI format required by BIDS, so it doubles the storage space needed.

My take would be here to use the BIDS strategy and have the raw data (accelerometer) and the derived data (activity counts) saved together in the standard data format (only raw is required). 

Does that make sense to you ?

**Comment by vincentvanhees** [comment]
Agree, that would be the best approach. If people are concerned about storage size then I think more energy should go towards ways of storing data more efficiently, e.g. avoid duplication and more efficient formats.

Good to know this repo is public now,  I thought this was an internal discussion in a private repo.
